{% set version = "0.4.5" %}

package:
  name: scikit-mdr
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/scikit-mdr/scikit-MDR-{{ version }}.tar.gz
  sha256: 05b9a6a7835b0362866ae3c64fbe94535b9f91e6f2ebfd596a424622627aa03b

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -v --no-deps"

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - matplotlib-base
    - numpy
    - python >=3.6
    - scikit-learn
    - scipy

test:
  source_files:
    - tests.py
  requires:
    # TODO: remove this pin, as the compatible version outside of NEP29
    - numpy <1.20
    - pip
    - pytest-cov
  imports:
    - mdr
  commands:
    - pip check
    - pytest -vv tests.py --cov=mdr --cov-report=term-missing:skip-covered --no-cov-on-fail

about:
  home: https://github.com/EpistasisLab/scikit-mdr
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: |
    A sklearn-compatible Python implementation of Multifactor Dimensionality
    Reduction (MDR) for feature construction.

  description: |
    MDR is an effective feature construction algorithm that is capable of
    modeling higher-order interactions and capturing complex patterns in data
    sets.

    MDR currently only works with categorical features and supports both binary
    classification and regression problems. We are working on expanding the
    algorithm to cover more problem types and provide more convenience features.
  dev_url: https://github.com/EpistasisLab/scikit-mdr

extra:
  recipe-maintainers:
    - bollwyvl
    - lacava
    - rhiever
    - weixuanfu
    - jay-m-dev
