travis:
  secure:
    BINSTAR_TOKEN: qDVm+rPnK+aQaSuuu1hdtQFj7BJoKDEcd972DXSZ0EQWnNDiQW3byT6eK/JdfkwcBcfu1c1SqM/8A7TuznpyG0jQTCsYb+r7bp3CQ7oR75YxIR2fcRgxrq/1AIVmdyeLvkd2j26GjDYioxzvGfFVpidb9pZEHUMSk6f+eIUcJMBRvi8cLIDuAM44h874hW/9Cy2Rtql23XkB0MSErBYBtwVj72gfMmjEDZbDoq5M+BK3dTnLqczRbvQr9oRxnCZFFfrnE5BI+RjeuQAsnnseOWLPwZXjIKhNiquJ2VlQuLAC8ne1iaqFtpLLG+QsXewwkiy44eVWXwCkCsnRnH/ImJ3duXhaPnlwf9N9an+qYSJX+r8g78y59q9ZygGMtaPaeH6qILVKRxcXt6gT9p4VNNQzBY+V/m/I5ZMXVpTtyKllZDUhGLhp6+klSbSzlChIYQukqec8MXrqLt3gv/p1weoZVN8MjrnIYf6Lg5cITr/KrJhtuHpNy1yy4TcPBgjjwJEMYXRe/pPq8E+8ngdprGZT1R5FEPnrDriFdFpCLO2ktraT5wV/LG+H+eaoa3lF57z2lPf7lD8GrPwGYioH5ZzZkzMhl4zUDw9nZoCPTyUD6MyUA3SRTN3wOTdhx9jRbkm4a+bGx/EbVJ6hqKsyARR3Kw4/T/BiACeBDBp15YI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
